### ISSUE TITLE
小游戏玩法设计

### ISSUE THREAD

**Issue by Shimogawa** [chuigda/Project-705#15]

**Comment by chuigda** [comment]
与其说这个东西是“地图设计”，不如说是我们要在屏幕上做一个小游戏，然后让这个小游戏可以跟游戏的其他部分（属性点，三相之力，技能，飞升，外交）等环节交互。考虑到 @Shimogawa 和原先的策划 @Aliceckx 都不喜欢挖cai脑di洞lei，以及踩地雷确实跟其他部分缺乏正交性。所以我们计划重新设计一下这个环节。

目前候选的模式包括
- 爬塔（杀戮尖塔/Inscryption）
- 自走棋
- 打牌
- Microsoft Store上有个地道挖矿的游戏，有点类似扫雷
- 飞行棋/大富翁
- 姐就是女王

无论如何，必须设法让这个minigame与游戏的其他内容良好地组合，并且平衡其中的随机性和确定性。此外minigame花的时间不能太长，不然“早上7:00开一局，6:00就结束了”。

**Comment by chuigda** [comment]
首先我们排除掉需要写AI的那部分选项（虽然小飞翔可能会写）

**Comment by chuigda** [comment]
![图片](https://user-images.githubusercontent.com/29348140/190859826-f597e34e-9e58-40b7-a91b-5b58d23dce79.png)

**Comment by chuigda** [comment]
![图片](https://user-images.githubusercontent.com/29348140/190903209-677262cd-d914-4109-8fa9-a899b8a6553c.png)

**Comment by CousinZe** [comment]
Letme help

**Comment by chuigda** [comment]
![24X (BB(5Z6K)CCUY 80D{R](https://user-images.githubusercontent.com/29348140/190911239-3e7bf04c-ac18-40fb-a258-98e0d9d02933.jpg)

**Comment by chuigda** [comment]
![chat-message](https://user-images.githubusercontent.com/29348140/190945429-59d1e90c-9f8d-4ce7-a603-30f20cdb380b.jpg)

**Comment by chuigda** [comment]
实现的部分就交给@Shimogawa了
