### ISSUE TITLE
GFX system

### ISSUE THREAD

**Issue by CousinZe** [chuigda/Project-705#35]
游戏中很多地方都会用到自定义资源，需要有一个统一的GFX系统来管理这些资源

**Comment by chuigda** [comment]
简单来说这套系统就是关于
- ruleset 中如何将 ruleset 定义的资源 (主要是图) 和一个全局的 identifier (参考`backstage/src/base/uid.ts`) 关联起来
- 前端使用全局identifier请求资源的时候，将对应的资源发送给前端

因为不涉及“业务”上的内容，所以相对比较简单，但可以帮助初步理解 compilation 和 mod loading 环节。

**Comment by chuigda** [comment]
Replaced by #52
