### ISSUE TITLE
Upgrade to node 18

### ISSUE THREAD

**Issue by Shimogawa** [chuigda/Project-705#45]
Node 16 [EOL in 10 mo.](https://endoflife.date/nodejs)

Upgrade to node 18

**Comment by chuigda** [comment]
I've added a new workflow to build and test our project with node 18, and it passes. I think we can keep everything else as-is, and developers may migrate to node 18 at their own will, gradually.

**Comment by CousinZe** [comment]
I think another workflow for frontend needs to be added.

**Comment by Shimogawa** [comment]
Should this be changed?
```diff
   "devDependencies": {
     "@types/express": "^4.17.13",
-    "@types/node": "^16",
+    "@types/node": "^18",
     "@types/uuid": "^8.3.4",
```

**Comment by chuigda** [comment]
> Should this be changed?
> 
> ```diff
>    "devDependencies": {
>      "@types/express": "^4.17.13",
> -    "@types/node": "^16",
> +    "@types/node": "^18",
>      "@types/uuid": "^8.3.4",
> ```

Since these are just type definitions, and these definitions from node16 seems to work somehow with node 18, I think there's no need of changing it until we all switch to node 18.
